# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_of_birth', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱')),
                ('username', models.CharField(default='', max_length=255, unique=True, verbose_name='用户名')),
                ('sex', models.CharField(blank=True, choices=[('man', '男'), ('female', '女'), ('unknown', '女')], default='man', max_length=15, verbose_name='性别')),
                ('thumb', models.ImageField(default='/user/thumbnails/default_thumb.png', upload_to='user/thumbnails', verbose_name='头像')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('expires_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登陆过期时间')),
                ('nickname', models.CharField(blank=True, default='', max_length=255, verbose_name='昵称')),
                ('userid', models.CharField(blank=True, default='b133d8a2015035e6be0785e2fd15cfb9', max_length=100, unique=True, verbose_name='用户ID')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
    ]
