# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '首页',
                'verbose_name': '首页',
                'db_table': 'index_indexmodel',
            },
        ),
    ]
